# Generated by Django 4.1.2 on 2022-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):  #clasa care mosteneste migrarile, creata automat

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel( #acestea sunt campurile care vor fi adaugate in baza de date
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
